### ISSUE TITLE
Support In-Memory Memory Storage for Easier Setup

### ISSUE THREAD

**Issue by gromdimon** [axioma-ai-labs/nevron#1]
### **Issue Description**
Currently, the `MemoryModule` relies on Qdrant, which requires running an external service. This can be a barrier for some users who need a lightweight or in-memory solution for local or temporary use. To improve usability, the `MemoryModule` should support an in-memory backend that works out of the box without additional dependencies.

The goal is to wrap the memory storage functionality in a unified interface so that users can choose between using Qdrant (persistent, service-based) or an in-memory storage backend.

---

### **Task Requirements**
1. Implement an **in-memory backend** for the `MemoryModule` that behaves similarly to Qdrant.
2. Wrap the memory storage logic in a single interface so the user can switch backends easily.
3. Ensure the current methods (`store` and `search`) remain consistent, with minimal or no changes required by the calling code.
4. Add documentation for the new feature, explaining how users can configure the memory backend.
5. Write unit tests to verify the behavior of both Qdrant and in-memory backends.

---

### **Specifications**
1. **Add Backend Configuration**:
   - Extend the `MemoryModule` constructor to accept a `backend` parameter:
     ```python
     def __init__(self, backend: str = "qdrant", **kwargs):
         """
         Args:
             backend (str): The memory backend to use ('qdrant' or 'in-memory').
         """
     ```

2. **Implement an In-Memory Backend**:
   - Use Python’s dictionaries and lists to emulate vector storage and similarity search.
   - Define a class `InMemoryStorage` with methods `store` and `search`.

3. **Integrate Backend Switching**:
   - Add logic in the `MemoryModule` to delegate `store` and `search` calls to the appropriate backend (either Qdrant or in-memory).

4. **Minimal Change to Current Methods**:
   - The user-facing interface (`store` and `search`) should remain unchanged.

5. **Unit Tests**:
   - Test both backends for storing and searching data.
   - Ensure the results match for both backends when used in equivalent scenarios.

---

### **Step-by-Step Implementation**
1. **Update `MemoryModule` Constructor**:
   - Add a `backend` parameter to switch between Qdrant and in-memory implementations:
     ```python
     def __init__(self, backend: str = "qdrant", **kwargs):
         self.backend = backend
         if backend == "qdrant":
             self._backend = QdrantBackend(**kwargs)
         elif backend == "in-memory":
             self._backend = InMemoryBackend()
         else:
             raise ValueError(f"Unsupported backend: {backend}")
     ```

2. **Implement `InMemoryBackend`**:
   - Create a lightweight in-memory storage class:
     ```python
     class InMemoryBackend:
         def __init__(self):
             self.memory = []  # List of {'id': ..., 'vector': ..., 'payload': ...}

         def store(self, content: str, metadata: Optional[Dict[str, Any]] = None) -> None:
             embedding = my_embedding_function(content)
             point_id = str(uuid.uuid4())
             payload = {"content": content, **(metadata or {})}
             self.memory.append({"id": point_id, "vector": embedding, "payload": payload})

         def search(self, query: str, top_k: int = 3) -> List[Dict[str, Any]]:
             query_vector = my_embedding_function(query)
             results = []
             for point in self.memory:
                 score = self._cosine_similarity(query_vector, point["vector"])
                 results.append({"content": point["payload"]["content"], "metadata": point["payload"], "score": score})
             results.sort(key=lambda x: x["score"], reverse=True)
             return results[:top_k]

         @staticmethod
         def _cosine_similarity(vec1: List[float], vec2: List[float]) -> float:
             dot_product = sum(a * b for a, b in zip(vec1, vec2))
             norm1 = sum(a * a for a in vec1) ** 0.5
             norm2 = sum(b * b for b in vec2) ** 0.5
             return dot_product / (norm1 * norm2)
     ```

3. **Refactor `MemoryModule` to Use Backends**:
   - Delegate `store` and `search` to the selected backend:
     ```python
     def store(self, content: str, metadata: Optional[Dict[str, Any]] = None) -> None:
         self._backend.store(content, metadata)

     def search(self, query: str, top_k: int = 3) -> List[Dict[str, Any]]:
         return self._backend.search(query, top_k)
     ```

4. **Add Documentation**:
   - Explain how to select the backend:
     ```python
     # Example Usage
     memory = MemoryModule(backend="in-memory")
     memory.store("Some important news", metadata={"source": "news"})
     results = memory.search("important")
     print(results)
     ```
---

### **Acceptance Criteria**
- [ ] `MemoryModule` supports both Qdrant and in-memory backends via a unified interface.
- [ ] Both backends pass unit tests for storing and searching.
- [ ] Minimal or no changes to the public `store` and `search` methods.
- [ ] Clear documentation for switching between backends.

---

### **Estimated Complexity**: Medium  
This task involves creating the `InMemoryBackend`, refactoring `MemoryModule`, and ensuring both options work seamlessly. The unit tests and documentation will ensure quality.
