### ISSUE TITLE
Implement search with perplexity

### ISSUE THREAD

**Issue by gromdimon** [axioma-ai-labs/nevron#12]
### **Issue Description**

Implement a new tool `search_with_perplexity` to fetch the latest news about cryptocurrencies using the Perplexity API. This tool will allow the agent to perform efficient and targeted searches for crypto-related news, ensuring relevance and recency.

The tool will:
1. **Query the Perplexity API**: Use an appropriate query structure to retrieve crypto news.
2. **Process and Format Results**: Parse the API response and extract relevant information for display.
3. **Handle Errors Gracefully**: Provide fallback messages in case of errors or missing results.

---

#### 1. **Define `search_with_perplexity` Function**
- Use the provided example as a base to create a function that queries the Perplexity API with a crypto-related query.
- Add support for specific parameters like domain filters, recency filters, and structured formatting.

#### 2. **Include Configuration in Settings**
- Add the following configuration options to `settings`:
  - `PERPLEXITY_API_KEY`: API key for authenticating with the Perplexity API.
  - `PERPLEXITY_ENDPOINT`: API endpoint for sending search queries.

#### 3. **Support Crypto News Queries**
- Focus on fetching the latest news about cryptocurrencies.
- Use queries like `"Latest cryptocurrency news"` or `"Breaking news in crypto"` to refine results.

#### 4. **Format Results**
- Parse the Perplexity API response to extract summaries, highlights, and key information.
- Format the results for readability, suitable for both console output and integration with other workflows.

#### 5. **Handle Errors and Edge Cases**
- Provide meaningful fallback messages for scenarios like:
  - Missing or invalid API keys.
  - API response errors or timeouts.
  - No results found for the query.

---

#### 1. **Add `search_with_perplexity` to Tools**
Implement the function:
```python
import httpx
from loguru import logger
from src.core.config import settings
from src.core.exceptions import APIError


async def search_with_perplexity(query: str) -> str:
    """
    Perform a Perplexity search for the latest cryptocurrency news.

    Args:
        query (str): The search query (e.g., "Latest cryptocurrency news").

    Returns:
        str: Search results or an error message.
    """
    try:
        if not settings.PERPLEXITY_API_KEY:
            raise APIError("Perplexity API key is not set")

        payload = {
            "model": "llama-3.1-sonar-small-128k-online",
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "You are a capable and efficient search assistant. "
                        "Your job is to find relevant and concise information about cryptocurrencies "
                        "based on the query provided."
                    ),
                },
                {
                    "role": "user",
                    "content": f"Search for the latest cryptocurrency news: {query}",
                },
            ],
            "temperature": 0.5,
            "top_p": 1.0,
            "search_domain_filter": ["perplexity.ai"],  # Use default domain filter
            "return_images": False,
            "return_related_questions": False,
            "stream": False,
        }

        headers = {
            "Authorization": f"Bearer {settings.PERPLEXITY_API_KEY}",
            "Content-Type": "application/json",
        }

        async with httpx.AsyncClient() as client:
            response = await client.post(
                settings.PERPLEXITY_ENDPOINT, json=payload, headers=headers
            )
            response.raise_for_status()
            data = response.json()

        logger.debug("Perplexity Search | Successfully retrieved results.")
        summary = data.get("summary", "No summary available.")
        return f"Perplexity Search Results:\n{summary}"
    except Exception as e:
        logger.error(f"Error during Perplexity search: {str(e)}")
        return "Perplexity search data is currently unavailable."
```

#### 2. **Update Settings**
- Add the following settings to `core/config.py`:
  ```python
  PERPLEXITY_API_KEY = "your_api_key_here"
  PERPLEXITY_ENDPOINT = "https://api.perplexity.ai/search"
  ```

#### 3. **Test the Function**
- Use mock queries to test the function:
  - Query: `"Latest cryptocurrency news"` or similar
  - Validate the results for relevance and clarity.
- Test error handling with:
  - Missing API key.
  - Invalid API response structure.
  - Timeout scenarios.

#### 4. **Document the Function**
Add documentation to describe:
- Input: Search query (string).
- Output: Formatted string with results or error message.
- Expected behavior in error scenarios.

---

### **TODO**
- [ ] `search_with_perplexity` function is implemented and integrated into the tools module.
- [ ] Settings for API key and endpoint are added to the config.
- [ ] Implement proper logging/ error handling.
- [ ] Documentation is updated to describe the function and its usage.

---

### **Estimated Complexity**: Medium  
This task involves integrating with an external API, handling errors, and formatting results for downstream usage.
